[package]
name = "rumblebot"
version = "0.1.0"
authors = ["Anton <antonoutkine@gmail.com>", "Noah <33094578+coolreader18@users.noreply.github.com>"]
edition = "2018"

[dependencies]
logic = { path = "../logic/logic" }

tokio = { version = "0.2", features = ["process", "macros"] }
futures-util = "0.3"

native-runner = { path = "../logic/runners/native" }
wasi-runner = { path = "../logic/runners/wasi" }
wasmer-runtime = "0.16"
wasmer-wasi = "0.16"

anyhow = "1.0"
itertools = "0.9"
tempfile = "3"
clap = "2"
shell-words = "1.0"
once_cell = "1.3"
dirs = "2.0"
async-trait = "0.1"
