[package]
name = "rumblebot"
version = "0.1.0"
authors = ["Anton <antonoutkine@gmail.com>", "Noah <33094578+coolreader18@users.noreply.github.com>"]
edition = "2018"

[dependencies]
logic = { path = "../logic/logic" }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
serde_with = "1.4"

tokio = { version = "0.2", features = ["process", "macros", "io-std"] }
futures-util = "0.3"
warp = "0.2"
static_dir = "0.1"
webbrowser = "0.5"
reqwest = { version = "0.10", features = ["cookies", "json"] }

native-runner = { path = "../logic/runners/native" }
wasi-runner = { path = "../logic/runners/wasi" }
wasmer-runtime = "0.16"
wasmer-wasi = "0.16"

anyhow = "1.0"
itertools = "0.9"
tempfile = "3"
structopt = "0.3"
shell-words = "1.0"
once_cell = "1.3"
dirs = "2.0"
confy = "0.4"
async-trait = "0.1"
owning_ref = "0.4"
rpassword = "4"
strum = { version = "0.18", features = ["derive"] }
