[package]
name = "rumblebot"
version = "0.1.0"
authors = ["Anton <antonoutkine@gmail.com>", "Noah <33094578+coolreader18@users.noreply.github.com>"]
edition = "2018"

[dependencies]
logic = { path = "../logic/logic" }
serde = { version = "1.0.114", features = ["derive"] }
serde_json = "1.0.55"
serde_with = "1.4.0"

tokio = { version = "0.2.21", features = ["process", "macros", "io-std"] }
futures-util = "0.3.5"
warp = "0.2.3"
static_dir = "0.1.3"
webbrowser = "0.5.4"
reqwest = { version = "0.10.6", features = ["cookies", "json"] }

native-runner = { path = "../logic/env-runners/native" }
wasi-process = "0.1"
wasmer-runtime = "0.17.0"
wasmer-wasi = "0.17.0"

anyhow = "1.0.31"
itertools = "0.9.0"
tempfile = "3.1.0"
structopt = "0.3.15"
shell-words = "1.0.0"
once_cell = "1.4.0"
dirs = { package = "dirs-next", version = "1.0" }
confy = "0.4.0"
async-trait = "0.1.36"
owning_ref = "0.4.1"
rpassword = "4.0.5"
strum = { version = "0.18.0", features = ["derive"] }


# https://github.com/sfackler/rust-openssl/issues/980#issuecomment-415757400
# Add openssl-sys as a direct dependency so it can be cross compiled to
# x86_64-unknown-linux-musl using the "vendored" feature below
openssl-sys = "0.9.58"

[features]
# Force openssl-sys to staticly link in the openssl library. Necessary when
# cross compiling to x86_64-unknown-linux-musl.
vendored = ["openssl-sys/vendored"]
