on:
  push:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
      - uses: actions/checkout@v2

      - uses: actions/cache@v2
        with:
          path: ~/.cargo
          key: cargo-${{ matrix.os }}-${{ hashFiles('Cargo.lock') }}
      - uses: actions/cache@v2
        with:
          path: target
          key: build-${{ matrix.os }}

      - uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - run: git clone https://github.com/robot-rumble/logic ../logic
      - run: aws s3 sync s3://${{ secrets.S3_BUCKET }}/lang-runners ../logic/wasm-dist/lang-runners
      - run: aws s3 sync s3://${{ secrets.S3_BUCKET }}/cli-assets dist

      - run: cargo build --release --all-features

      - if: matrix.os == 'windows-latest'
        run: aws s3 cp target/release/rumblebot.exe s3://${{ secrets.S3_BUCKET }}/cli-build/rumblebot-windows.exe

      - if: matrix.os == 'macos-latest' || matrix.os == 'ubuntu-latest'
        run: aws s3 cp target/release/rumblebot s3://${{ secrets.S3_BUCKET }}/cli-build/rumblebot-${{ matrix.os }}
